# Generated by Django 4.1.7 on 2023-03-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/users_img'),
        ),
    ]
