# Generated by Django 4.1.7 on 2023-03-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('account_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('full_game_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('account_details', models.TextField(blank=True, null=True)),
                ('rental_time', models.CharField(blank=True, max_length=64, null=True)),
                ('key', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('image_page', models.ImageField(upload_to='page_photo')),
                ('video_link', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.category')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_method', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.products')),
                ('purchaseMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.purchasemethod')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publisher'),
        ),
        migrations.AddField(
            model_name='products',
            name='purchaseMethod',
            field=models.ManyToManyField(through='games.purchase', to='games.purchasemethod'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.products')),
                ('purchaseMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
