# Generated by Django 4.1.7 on 2023-03-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_method', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.purchasemethod'),
        ),
    ]
