# Generated by Django 4.1.7 on 2023-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_basket_purchasemethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='account_details',
        ),
        migrations.RemoveField(
            model_name='products',
            name='account_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='full_game_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='key',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rental_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rental_time',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_data',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
