# Generated by Django 4.1.7 on 2023-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_purchasemethod_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rental_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
