# Generated by Django 4.1.7 on 2023-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
