# Generated by Django 4.1.7 on 2023-04-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_products_release'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-release']},
        ),
        migrations.AddField(
            model_name='purchasemethod',
            name='timeframe',
            field=models.IntegerField(default=500),
        ),
    ]
