# Generated by Django 4.1.7 on 2023-03-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_slider_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='purchase_method',
        ),
        migrations.CreateModel(
            name='name_purchaseMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.products')),
                ('purchase_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.purchasemethod')),
            ],
        ),
    ]
